### PR TITLE
delete your account xd

### PR DESCRIPTION
**Pull request by pigeonlol**

### CODE REVIEW

**Comment by KYXWARE** [comment]
Lmao Pigeon stfu with ur Token Logger HAHAH

**Comment by pigeonlol** [comment]
ok

**Comment by KYXWARE** [comment]
Lmao nothing of it is a Paste.

**Comment by pigeonlol** [comment]
ok

**Comment by KYXWARE** [comment]
Lmao that wasn‘t even my Source Code it was one from my Friend but ok.

**Comment by KYXWARE** [comment]
Also your source code is shit asf

**Comment by pigeonlol** [comment]
ok

**Comment by KYXWARE** [comment]
I don‘t use api anymore Lmao 😝

**Comment by pigeonlol** [comment]
explain how to dump addys

**Comment by pigeonlol** [comment]
explain how to replace addys

**Comment by pigeonlol** [comment]
thats what i though retard now u quite asf

**Pull request closed without merging**
